### ISSUE TITLE
Slave Readiness Probes faling 

### ISSUE THREAD

**Issue by NishikaDeSilva** [vromero/activemq-artemis-helm#37]
Hi, 

I'm trying to deploy ActiveMQ-Artemis helm chart. But the slave's readiness probe fails. 

<img width="1554" alt="Screen Shot 2019-10-01 at 5 20 48 PM" src="https://user-images.githubusercontent.com/47025945/66181703-6292a400-e68f-11e9-8524-41602972da1c.png">

How can I find the base issue ?

**Comment by Namphibian** [comment]
Slaves wont be ready till there is a failover. This is by design.

**Comment by bendahl** [comment]
Hi,

I just stumbled upon the same issue and was wondering why the slaves' readiness probes kept failing. As @Namphibian already mentioned, this is by design. In case anyone is wondering why this is, take a look at this:

https://activemq.apache.org/pure-master-slave

and:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

Reading through those documents should clarify a) why the salves will refuse connections and b) why it makes sense to use a readiness probe for that sort of scenario. So all in all a feature, not a bug.

That leaves the question whether this issue should be closed...

Cheers

**Comment by vromero** [comment]
You are right. This is a very bothersome problem, as it does create problems in regular usage, e.g: helm install ... --wait

I'm still thinking about what to do with this, it might easily happen that the readiness is handled by a script and JMX and the loadbalancer is removed and the clients exptected to configure manually. Not sure yet. I did create an issue to have office hours but still hoping (waiting) for @dansalt to appear as he has contributed multiple times.
